language: node_js
node_js:
  - "iojs-v3.3"
  - "iojs-v3.0"
  - "iojs-v2.5"
  - "iojs-v2.0"
  - "iojs-v1.8"
  - "iojs-v1.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - "0.6"
  - "0.4"
sudo: false
matrix:
  allow_failures:
    - node_js: "iojs-v2.5"
    - node_js: "iojs-v2.0"
    - node_js: "iojs-v1.8"
    - node_js: "iojs-v1.0"
    - node_js: "0.12"
    - node_js: "0.11"
    - node_js: "0.10"
    - node_js: "0.9"
    - node_js: "0.8"
    - node_js: "0.6"
    - node_js: "0.4"
addons:
  code_climate:
    repo_token: 599dca21bbd6845609f087cf0590d24011a560cc13506e10a0d30d4a8bdabb20
script: "npm run coverage"
after_script:
  - codeclimate-test-reporter < etc/lcov.info